import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    kotlin("jvm") version "1.3.71"
    id("java")
    id("war")
    id("org.gretty") version "3.0.2"
    id("org.seasar.doma.compile") version "1.0.0"
    kotlin("kapt") version "1.3.71"

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // auth0
    implementation("com.auth0:mvc-auth-commons:1.2.0")

    // https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    implementation("org.slf4j", "slf4j-api","1.7.25")

    implementation("io.github.config4k", "config4k", "0.4.1")

    // https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
    implementation("org.xerial", "sqlite-jdbc", "3.30.1")

    // https://mvnrepository.com/artifact/org.seasar.doma/doma
    kapt("org.seasar.doma:doma:2.29.0")
    implementation("org.seasar.doma:doma:2.29.0")

    // https://mvnrepository.com/artifact/org.springframework/spring-webmvc
    implementation("org.springframework", "spring-webmvc", "5.2.5.RELEASE")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api
    providedCompile("javax.servlet", "javax.servlet-api", "3.0.1")
}

application {
    // Define the main class for the application.
    mainClassName = "test.web.kotlin.AppKt"
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "11"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "11"
}

gretty {
    httpPort = 8888
    recompileOnSourceChange = true
}

task("domaTest") {
    application {
        mainClassName = "test.web.kotlin.DomaTestKt"
    }
}